#ifndef RFIDCOMPONENT_GLOBAL_H
#define RFIDCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RFIDCOMPONENT_LIBRARY)
#  define RFIDCOMPONENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RFIDCOMPONENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RFIDCOMPONENT_GLOBAL_H
