#ifndef CHARITYCOMPONENT_GLOBAL_H
#define CHARITYCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHARITYCOMPONENT_LIBRARY)
#  define CHARITYCOMPONENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHARITYCOMPONENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHARITYCOMPONENT_GLOBAL_H
