#ifndef LOGINCOMPONENT_GLOBAL_H
#define LOGINCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGINCOMPONENT_LIBRARY)
#  define LOGINCOMPONENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOGINCOMPONENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGINCOMPONENT_GLOBAL_H
