#ifndef VIEWSQLCOMPONENT_GLOBAL_H
#define VIEWSQLCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIEWSQLCOMPONENT_LIBRARY)
#  define VIEWSQLCOMPONENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VIEWSQLCOMPONENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VIEWSQLCOMPONENT_GLOBAL_H
